Repository TTB-Network/python-openbmclapi, pull requests merged in 2024-04, with the labels that each got.

#29 🐛 trust 直线下滑
  bmclapi_dashboard/static/js/index.js
  bmclapi_dashboard/static/js/index.min.js
  bmclapi_dashboard/static/js/ttb.js
  bmclapi_dashboard/static/js/ttb.min.js
  core/__init__.py
  core/api.py
  core/cluster.py
  core/config.py
  core/const.py
  core/dashboard.py
  core/logger.py
  core/stats.py
  core/system.py
  core/timer.py
  core/utils.py
  core/web.py
Labels: 漏洞, 改进, 高优先级

#35 修复pip认为--no-deps是要安装的依赖文件的名称的问题
  README.md
Labels: 文档

#36 ✨ 更新 Dashboard，i18n 以及 cluster
  README.md
  bmclapi_dashboard/index.html
  bmclapi_dashboard/static/js/index.min.js
  config/config.yml.example
  core/__init__.py
  core/api.py
  core/certificate.py
  core/cluster.py
  core/config.py
  core/const.py
  core/dashboard.py
  core/exceptions.py
  core/i18n.py
  core/logger.py
  core/stats.py
  core/timer.py
  core/utils.py
  core/web.py
  i18n/zh_cn.json
Labels: 漏洞, 改进

#47 🐛 修复漏洞
  .gitignore
  README.md
  bmclapi_dashboard/index.html
  bmclapi_dashboard/static/css/boxicons.min.css
  bmclapi_dashboard/static/fonts/Mono.ttf
  bmclapi_dashboard/static/fonts/Mono.woff2
  bmclapi_dashboard/static/js/index.min.js
  config/config.yml.example
  core/__init__.py
  core/certificate.py
  core/cluster.py
  core/config.py
  core/const.py
  core/dashboard.py
  core/database.py
  core/env.py
  core/exceptions.py
  core/location.py
  core/network.py
  core/scheduler.py
  core/stats.py
  core/system.py
  core/timer.py
  core/timings.py
  core/unit.py
  core/update.py
  core/utils.py
  core/web.py
  i18n/zh_cn.json
  main.py
Labels: 漏洞, 改进
